// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: BTHome v2_xG24_xG27_sensors_with_LVGL

#ifndef _BTHOME_V2_XG24_XG27_SENSORS_WITH_LVGL_UI_H
#define _BTHOME_V2_XG24_XG27_SENSORS_WITH_LVGL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_BootScreen.h"
#include "screens/ui_ApplicationScreen.h"
#include "screens/ui_SettingScreen.h"
#include "screens/ui_TSCalibrationScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1597985048);    // assets/silicon-labs-logo-red-2014-200px.png
LV_IMG_DECLARE(ui_img_25_png);    // assets/25.png
LV_IMG_DECLARE(ui_img_lvgl_logo_78_24_png);    // assets/lvgl_logo_78_24.png
LV_IMG_DECLARE(ui_img_30_60_png);    // assets/30_60.png
LV_IMG_DECLARE(ui_img_35_67_png);    // assets/35_67.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
