// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: BTHome v2_xG24_xG27_sensors_with_LVGL

#ifndef UI_APPLICATIONSCREEN_H
#define UI_APPLICATIONSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ApplicationScreen
extern void ui_ApplicationScreen_screen_init(void);
extern void ui_ApplicationScreen_screen_destroy(void);
extern lv_obj_t * ui_ApplicationScreen;
extern lv_obj_t * ui_Bar1;
extern void ui_event_imgbthome(lv_event_t * e);
extern lv_obj_t * ui_imgbthome;
extern void ui_event_imglvgl(lv_event_t * e);
extern lv_obj_t * ui_imglvgl;
extern lv_obj_t * ui_imgsilabs;
extern lv_obj_t * ui_imgzephyr;
extern lv_obj_t * ui_labeltextSi7021;
extern lv_obj_t * ui_labelTempValue;
extern lv_obj_t * ui_labelcelciousSymbol;
extern lv_obj_t * ui_labelhumidityValue;
extern lv_obj_t * ui_labelhumiditypercent;
extern lv_obj_t * ui_labelVEML6035;
extern lv_obj_t * ui_labelSI7210Hall;
extern lv_obj_t * ui_labelBMP384Barometric;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_labelICM20689;
extern lv_obj_t * ui_labelVEMLAmbientLightValue;
extern lv_obj_t * ui_labellxsymbol;
extern lv_obj_t * ui_labelsi7210HallEffectValue;
extern lv_obj_t * ui_labelmTSymbol;
extern lv_obj_t * ui_labelBMP384Value;
extern lv_obj_t * ui_labelmBarSymbol;
extern lv_obj_t * ui_labelOrientation;
extern lv_obj_t * ui_labelorientXvalue;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_labelDegreesymbol1;
extern lv_obj_t * ui_labelorientYvalue;
extern lv_obj_t * ui_labelDegreesymbol2;
extern lv_obj_t * ui_labelorientZvalue;
extern lv_obj_t * ui_labelDegreesymbol3;
extern lv_obj_t * ui_labelAcceleration;
extern lv_obj_t * ui_labelg1Value;
extern lv_obj_t * ui_labelGSymbol1;
extern lv_obj_t * ui_labelg2Value;
extern lv_obj_t * ui_labelGSymbol2;
extern lv_obj_t * ui_labelg3Value;
extern lv_obj_t * ui_labelGSymbol3;
extern lv_obj_t * ui_labelxg24;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_labelbroadcasted;
extern lv_obj_t * ui_labelsecond;
extern lv_obj_t * ui_labelsecago;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

