// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: BTHome v2_xG24_xG27_sensors_with_LVGL

#ifndef UI_BOOTSCREEN_H
#define UI_BOOTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BootScreen
extern void ui_BootScreen_screen_init(void);
extern void ui_BootScreen_screen_destroy(void);
extern lv_obj_t * ui_BootScreen;
extern lv_obj_t * ui_imgsilabsbig;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

