// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: BTHome v2_xG24_xG27_sensors_with_LVGL

#ifndef UI_SETTINGSCREEN_H
#define UI_SETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingScreen
extern void ui_SettingScreen_screen_init(void);
extern void ui_SettingScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingScreen;
extern lv_obj_t * ui_Bar5;
extern lv_obj_t * ui_imgBTHome;
extern lv_obj_t * ui_labelSetting;
extern void ui_event_btnback(lv_event_t * e);
extern lv_obj_t * ui_btnback;
extern lv_obj_t * ui_LabelBack;
extern lv_obj_t * ui_labelBoardcastenable;
extern lv_obj_t * ui_labelDeviceName;
extern lv_obj_t * ui_labelboardcastperiod;
extern lv_obj_t * ui_labelencryptkey;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_txtdevicename(lv_event_t * e);
extern lv_obj_t * ui_txtdevicename;
extern void ui_event_txtboardcastperiod(lv_event_t * e);
extern lv_obj_t * ui_txtboardcastperiod;
extern void ui_event_txtencryptkey(lv_event_t * e);
extern lv_obj_t * ui_txtencryptkey;
extern void ui_event_swboardcastenable(lv_event_t * e);
extern lv_obj_t * ui_swboardcastenable;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

