// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: BTHome v2_xG24_xG27_sensors_with_LVGL

#include "../ui.h"

lv_obj_t * uic_TSCalibrationScreen;
lv_obj_t * ui_TSCalibrationScreen = NULL;
lv_obj_t * ui_Bar6 = NULL;
lv_obj_t * ui_labelCalib = NULL;
lv_obj_t * ui_btnback1 = NULL;
lv_obj_t * ui_LabelBack1 = NULL;
lv_obj_t * ui_labelValueX = NULL;
lv_obj_t * ui_labelValueY = NULL;
lv_obj_t * ui_imgLVGLlogo = NULL;
lv_obj_t * ui_labelPointX = NULL;
lv_obj_t * ui_labelPointY = NULL;
lv_obj_t * ui_labelValueXmin = NULL;
lv_obj_t * ui_labelValueYmin = NULL;
lv_obj_t * ui_labelValueXmax = NULL;
lv_obj_t * ui_labelValueYmax = NULL;
lv_obj_t * ui_labelValueRTouch = NULL;
// event funtions
void ui_event_btnback1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        btn_back_callback(e);
    }
}

// build funtions

void ui_TSCalibrationScreen_screen_init(void)
{
    ui_TSCalibrationScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TSCalibrationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bar6 = lv_bar_create(ui_TSCalibrationScreen);
    lv_bar_set_value(ui_Bar6, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar6, 320);
    lv_obj_set_height(ui_Bar6, 1);
    lv_obj_set_x(ui_Bar6, 0);
    lv_obj_set_y(ui_Bar6, -90);
    lv_obj_set_align(ui_Bar6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Bar6, lv_color_hex(0x040000), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar6, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar6, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar6,
                                                                                           lv_obj_get_style_pad_right(ui_Bar6, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_labelCalib = lv_label_create(ui_TSCalibrationScreen);
    lv_obj_set_width(ui_labelCalib, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelCalib, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelCalib, -41);
    lv_obj_set_y(ui_labelCalib, -107);
    lv_obj_set_align(ui_labelCalib, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelCalib, "Touch Screen Calibration");
    lv_obj_set_style_text_font(ui_labelCalib, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnback1 = lv_button_create(ui_TSCalibrationScreen);
    lv_obj_set_width(ui_btnback1, 84);
    lv_obj_set_height(ui_btnback1, 24);
    lv_obj_set_x(ui_btnback1, 3);
    lv_obj_set_y(ui_btnback1, 80);
    lv_obj_set_align(ui_btnback1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnback1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnback1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnback1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnback1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_btnback1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBack1 = lv_label_create(ui_btnback1);
    lv_obj_set_width(ui_LabelBack1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBack1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBack1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBack1, "Back");

    ui_labelValueX = lv_label_create(ui_TSCalibrationScreen);
    lv_obj_set_width(ui_labelValueX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelValueX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelValueX, 4);
    lv_obj_set_y(ui_labelValueX, 68);
    lv_label_set_text(ui_labelValueX, "X:                   0");
    lv_obj_set_style_text_align(ui_labelValueX, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelValueX, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelValueY = lv_label_create(ui_TSCalibrationScreen);
    lv_obj_set_width(ui_labelValueY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelValueY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelValueY, 160);
    lv_obj_set_y(ui_labelValueY, 67);
    lv_label_set_text(ui_labelValueY, "Y:                   0");
    lv_obj_set_style_text_align(ui_labelValueY, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelValueY, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgLVGLlogo = lv_image_create(ui_TSCalibrationScreen);
    lv_image_set_src(ui_imgLVGLlogo, &ui_img_lvgl_logo_78_24_png);
    lv_obj_set_width(ui_imgLVGLlogo, LV_SIZE_CONTENT);   /// 78
    lv_obj_set_height(ui_imgLVGLlogo, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_imgLVGLlogo, 117);
    lv_obj_set_y(ui_imgLVGLlogo, -107);
    lv_obj_set_align(ui_imgLVGLlogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgLVGLlogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_imgLVGLlogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelPointX = lv_label_create(ui_TSCalibrationScreen);
    lv_obj_set_width(ui_labelPointX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPointX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPointX, 4);
    lv_obj_set_y(ui_labelPointX, 39);
    lv_label_set_text(ui_labelPointX, "PointX:        0");
    lv_obj_set_style_text_align(ui_labelPointX, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPointX, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelPointY = lv_label_create(ui_TSCalibrationScreen);
    lv_obj_set_width(ui_labelPointY, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelPointY, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelPointY, 161);
    lv_obj_set_y(ui_labelPointY, 40);
    lv_label_set_text(ui_labelPointY, "PointY:        0");
    lv_obj_set_style_text_align(ui_labelPointY, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelPointY, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelValueXmin = lv_label_create(ui_TSCalibrationScreen);
    lv_obj_set_width(ui_labelValueXmin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelValueXmin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelValueXmin, 4);
    lv_obj_set_y(ui_labelValueXmin, 95);
    lv_label_set_text(ui_labelValueXmin, "Xmin:           0");
    lv_obj_set_style_text_align(ui_labelValueXmin, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelValueXmin, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelValueYmin = lv_label_create(ui_TSCalibrationScreen);
    lv_obj_set_width(ui_labelValueYmin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelValueYmin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelValueYmin, 159);
    lv_obj_set_y(ui_labelValueYmin, 96);
    lv_label_set_text(ui_labelValueYmin, "Ymin:           0");
    lv_obj_set_style_text_align(ui_labelValueYmin, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelValueYmin, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelValueXmax = lv_label_create(ui_TSCalibrationScreen);
    lv_obj_set_width(ui_labelValueXmax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelValueXmax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelValueXmax, 4);
    lv_obj_set_y(ui_labelValueXmax, 124);
    lv_label_set_text(ui_labelValueXmax, "Xmax:          0");
    lv_obj_set_style_text_align(ui_labelValueXmax, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelValueXmax, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelValueYmax = lv_label_create(ui_TSCalibrationScreen);
    lv_obj_set_width(ui_labelValueYmax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelValueYmax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelValueYmax, 159);
    lv_obj_set_y(ui_labelValueYmax, 124);
    lv_label_set_text(ui_labelValueYmax, "Ymax:          0");
    lv_obj_set_style_text_align(ui_labelValueYmax, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelValueYmax, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelValueRTouch = lv_label_create(ui_TSCalibrationScreen);
    lv_obj_set_width(ui_labelValueRTouch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelValueRTouch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelValueRTouch, 4);
    lv_obj_set_y(ui_labelValueRTouch, 148);
    lv_label_set_text(ui_labelValueRTouch, "Rtouch:       0");
    lv_obj_set_style_text_align(ui_labelValueRTouch, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelValueRTouch, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnback1, ui_event_btnback1, LV_EVENT_ALL, NULL);
    uic_TSCalibrationScreen = ui_TSCalibrationScreen;

}

void ui_TSCalibrationScreen_screen_destroy(void)
{
    if(ui_TSCalibrationScreen) lv_obj_del(ui_TSCalibrationScreen);

    // NULL screen variables
    uic_TSCalibrationScreen = NULL;
    ui_TSCalibrationScreen = NULL;
    ui_Bar6 = NULL;
    ui_labelCalib = NULL;
    ui_btnback1 = NULL;
    ui_LabelBack1 = NULL;
    ui_labelValueX = NULL;
    ui_labelValueY = NULL;
    ui_imgLVGLlogo = NULL;
    ui_labelPointX = NULL;
    ui_labelPointY = NULL;
    ui_labelValueXmin = NULL;
    ui_labelValueYmin = NULL;
    ui_labelValueXmax = NULL;
    ui_labelValueYmax = NULL;
    ui_labelValueRTouch = NULL;

}
