// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: BTHome v2_xG24_xG27_sensors_with_LVGL

#ifndef UI_TSCALIBRATIONSCREEN_H
#define UI_TSCALIBRATIONSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TSCalibrationScreen
extern void ui_TSCalibrationScreen_screen_init(void);
extern void ui_TSCalibrationScreen_screen_destroy(void);
extern lv_obj_t * ui_TSCalibrationScreen;
extern lv_obj_t * ui_Bar6;
extern lv_obj_t * ui_labelCalib;
extern void ui_event_btnback1(lv_event_t * e);
extern lv_obj_t * ui_btnback1;
extern lv_obj_t * ui_LabelBack1;
extern lv_obj_t * ui_labelValueX;
extern lv_obj_t * ui_labelValueY;
extern lv_obj_t * ui_imgLVGLlogo;
extern lv_obj_t * ui_labelPointX;
extern lv_obj_t * ui_labelPointY;
extern lv_obj_t * ui_labelValueXmin;
extern lv_obj_t * ui_labelValueYmin;
extern lv_obj_t * ui_labelValueXmax;
extern lv_obj_t * ui_labelValueYmax;
extern lv_obj_t * ui_labelValueRTouch;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TSCalibrationScreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

